data_ingestion:
  test_size: 0.20
  random_state: 42

target_column: Attrition

model_trainer:
  model_name: svm

  C: 10

  kernel: linear

  gamma: scale

  class_weight: balanced

  probability: true

  random_state: 42
